// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0sYFP8BRAaOugmIPq8_Ws_LD4J77_MaU',
    appId: '1:125875526890:web:e18cceb412fd6012c70b93',
    messagingSenderId: '125875526890',
    projectId: 'treasurebook-38980',
    authDomain: 'treasurebook-38980.firebaseapp.com',
    storageBucket: 'treasurebook-38980.appspot.com',
    measurementId: 'G-YLDJ9F5P42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Tdq0c2nJnXFfZO5Mql_ukohQeCwrbJw',
    appId: '1:125875526890:android:4980bd871e96fac9c70b93',
    messagingSenderId: '125875526890',
    projectId: 'treasurebook-38980',
    storageBucket: 'treasurebook-38980.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoVYCjK3RMXuWZVRZKSR017OojgQt_2_M',
    appId: '1:125875526890:ios:c3ead16dc85b4344c70b93',
    messagingSenderId: '125875526890',
    projectId: 'treasurebook-38980',
    storageBucket: 'treasurebook-38980.appspot.com',
    iosBundleId: 'com.example.treasureBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoVYCjK3RMXuWZVRZKSR017OojgQt_2_M',
    appId: '1:125875526890:ios:c3ead16dc85b4344c70b93',
    messagingSenderId: '125875526890',
    projectId: 'treasurebook-38980',
    storageBucket: 'treasurebook-38980.appspot.com',
    iosBundleId: 'com.example.treasureBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0sYFP8BRAaOugmIPq8_Ws_LD4J77_MaU',
    appId: '1:125875526890:web:1ef90e2079c7dceec70b93',
    messagingSenderId: '125875526890',
    projectId: 'treasurebook-38980',
    authDomain: 'treasurebook-38980.firebaseapp.com',
    storageBucket: 'treasurebook-38980.appspot.com',
    measurementId: 'G-PWKCKH8L51',
  );
}
